[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
upload_protocol = teensy-cli

; Library dependencies - Hardware + Jazzy micro-ROS
lib_deps =
    # Use the specific Jazzy branch 
    https://github.com/micro-ROS/micro_ros_arduino.git#jazzy
    # Hardware Libraries
    adafruit/Adafruit BNO055 @ ^1.6.3
    adafruit/Adafruit BusIO @ ^1.16.1
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    sparkfun/SparkFun u-blox GNSS v3 @ ^3.1.5
    https://github.com/SolidGeek/VescUart

; Required build flags for Jazzy + Teensy 4.1
build_flags =
    # 1. Point to the EXACT folder containing libmicroros.a
    -L .pio/libdeps/teensy41/micro_ros_arduino/src/imxrt1062/fpv5-d16-hard/
    # 2. Tell the linker to use that file (it looks for 'lib' + 'microros' + '.a')
    -l microros
    -D USB_SERIAL
    # 3. Point to the folder containing the .h header files
    -I .pio/libdeps/teensy41/micro_ros_arduino/src/

monitor_speed = 115200